import {
  ArrowDown,
  ArrowRight,
  ArrowUpDown,
  BadgeCheck,
  Ban,
  Banknote,
  BarChart2,
  BarChart3,
  Bell,
  BellRing,
  Calendar,
  CalendarCheck,
  CalendarDays,
  Cast,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CirclePlay,
  CirclePlus,
  ClipboardList,
  Clock,
  Copy,
  Download,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Flame,
  Gift,
  GraduationCap,
  Hand,
  HeartHandshake,
  HelpCircle,
  History,
  Hourglass,
  IdCard,
  Info,
  Landmark,
  Layers,
  LayoutDashboard,
  Leaf,
  LineChart,
  Link,
  Lock,
  LogOut,
  MapPin,
  Medal,
  Menu,
  MessageCircle,
  Minus,
  NotebookPen,
  Package,
  Percent,
  Pill,
  Pencil,
  PiggyBank,
  Plus,
  Printer,
  QrCode,
  Receipt,
  Save,
  ScanFace,
  ScanLine,
  Scale,
  Search,
  Settings,
  Share2,
  Shield,
  ShieldUser,
  ShoppingBasket,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Star,
  Store,
  Table,
  Tag,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Upload,
  User,
  UserCheck,
  UserCog,
  UserPlus,
  UserSearch,
  Users,
  Vote,
  Wallet,
  Warehouse,
  Wheat,
  X,
  XCircle,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";

const ICON_MAP: Record<string, LucideIcon> = {
  account_balance: Landmark,
  account_balance_wallet: Wallet,
  add: Plus,
  add_circle: CirclePlus,
  agriculture: Wheat,
  analytics: BarChart3,
  app_registration: UserPlus,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  article: FileText,
  assignment_ind: ClipboardList,
  auto_awesome: Sparkles,
  badge: IdCard,
  balance: Scale,
  bar_chart: BarChart2,
  block: Ban,
  calendar_month: Calendar,
  calendar_today: CalendarDays,
  cancel: XCircle,
  cast: Cast,
  chat: MessageCircle,
  check: Check,
  check_circle: CircleCheck,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  circle: Circle,
  close: X,
  compost: Leaf,
  contactless: ScanLine,
  content_copy: Copy,
  dashboard: LayoutDashboard,
  delete: Trash2,
  description: FileText,
  download: Download,
  edit: Pencil,
  edit_note: NotebookPen,
  emoji_events: Trophy,
  error: CircleAlert,
  event: Calendar,
  event_available: CalendarCheck,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  face_retouching_natural: ScanFace,
  filter_list: Filter,
  group: Users,
  group_add: UserPlus,
  groups: Users,
  history: History,
  hourglass_top: Hourglass,
  how_to_reg: UserCheck,
  how_to_vote: Vote,
  id_card: IdCard,
  info: Info,
  inventory_2: Package,
  layers: Layers,
  leaderboard: Medal,
  link: Link,
  local_fire_department: Flame,
  local_grocery_store: ShoppingBasket,
  local_offer: Tag,
  local_pharmacy: Pill,
  location_on: MapPin,
  lock: Lock,
  logout: LogOut,
  menu: Menu,
  notifications: Bell,
  notifications_active: BellRing,
  payments: Banknote,
  pending_actions: Clock,
  people: Users,
  percent: Percent,
  person: User,
  person_add: UserPlus,
  person_outline: User,
  person_search: UserSearch,
  play_circle: CirclePlay,
  policy: Shield,
  print: Printer,
  qr_code_2: QrCode,
  qr_code_scanner: ScanLine,
  query_stats: LineChart,
  quiz: HelpCircle,
  radio_button_unchecked: Circle,
  receipt_long: Receipt,
  redeem: Gift,
  save: Save,
  savings: PiggyBank,
  schedule: Clock,
  school: GraduationCap,
  search: Search,
  sell: Tag,
  settings: Settings,
  share: Share2,
  shield: Shield,
  shield_person: ShieldUser,
  shopping_cart: ShoppingCart,
  stars: Star,
  storefront: Store,
  straighten: ScanLine,
  supervisor_account: UserCog,
  swap_vert: ArrowUpDown,
  table_chart: Table,
  thumb_down: ThumbsDown,
  thumb_up: ThumbsUp,
  touch_app: Hand,
  trending_down: TrendingDown,
  trending_flat: Minus,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  upload_file: Upload,
  verified: BadgeCheck,
  verified_user: BadgeCheck,
  visibility: Eye,
  visibility_off: EyeOff,
  volunteer_activism: HeartHandshake,
  warning: TriangleAlert,
  warehouse: Warehouse,
};

const DEFAULT_ICON = Circle;

export interface AppIconProps {
  name: string;
  className?: string;
  filled?: boolean;
}

export function AppIcon({ name, className, filled }: AppIconProps) {
  const Icon = ICON_MAP[name] ?? DEFAULT_ICON;

  return (
    <Icon
      className={cn(
        "inline-block size-[1em] shrink-0",
        filled && "fill-current",
        className,
      )}
      aria-hidden
    />
  );
}
